/**
 * Application-wide constants
 */

// Layout constants
export const LAYOUT = {
  // Lanes
  LANE_HEIGHT: 140,
  LANE_SPACING: 10,
  LANE_START_Y: 50,
  LANE_PADDING_X: 20,
  LANE_CORNER_RADIUS: 2,

  // Nodes
  NODE_WIDTH: 100,
  NODE_HEIGHT: 50,
  NODE_RADIUS: 35,
  NODE_CORNER_RADIUS: 25,
  NODE_CENTER_OFFSET: 70,
  NODE_SPACING: 200,
  NODE_START_X: 150,

  // Connections
  CONNECTION_ANCHOR_RADIUS: 8,
  CONNECTION_ANCHOR_DISTANCE: 35,
  CONNECTION_CURVE_OFFSET: 50,
  CONNECTION_CONTROL_OFFSET: 150,

  // Phases
  PHASE_CIRCLE_SPACING: 40,
  PHASE_CIRCLE_RADIUS: 6,
  PHASE_DEFAULT_WIDTH: 400,
  PHASE_LINE_WIDTH: 5,
  PHASE_DASH_PATTERN: '15, 5',

  // Canvas
  DEFAULT_CANVAS_WIDTH: 1440,
  DEFAULT_CANVAS_HEIGHT: 800,
  MIN_ZOOM_WIDTH: 200,
  MAX_ZOOM_WIDTH: 10000,

  // Margins
  MARGIN_SMALL: 10,
  MARGIN_MEDIUM: 20,
  MARGIN_LARGE: 40,
};

// Animation constants
export const ANIMATION = {
  TRANSITION_DURATION: 200,
  HOVER_OPACITY: 0.8,
  HIDDEN_OPACITY: 0,
  DRAG_OPACITY: 0.7,
};

// Storage constants
export const STORAGE = {
  MAX_URL_DATA_LENGTH: 100000,
  MAX_DECODED_DATA_LENGTH: 500000,
  MAX_HISTORY_SIZE: 50,
  LOCAL_STORAGE_KEY: 'swimlane_diagram',
};

// Colors
export const COLORS = {
  PHASE_RED: '#FF5722',
  PHASE_BLUE: '#2196F3',
  CONNECTION_ANCHOR: '#2196f3',
  CONNECTION_ANCHOR_ACTIVE: '#1976d2',
  NODE_STROKE: 'white',
  NODE_STROKE_WIDTH: '2',
};

// Z-Index layers
export const Z_INDEX = {
  LANES: 1,
  PHASES: 2,
  CONNECTIONS: 3,
  NODES: 4,
  TOOLTIPS: 1000,
  MODALS: 2000,
};

// Text sizes
export const FONT_SIZE = {
  NODE_ICON: '20px',
  NODE_TEXT: '12px',
  LANE_LABEL: '16px',
  PHASE_LABEL: '14px',
  CONNECTION_LABEL: '11px',
  TOOLTIP: '14px',
};

// Validation limits
export const LIMITS = {
  MAX_LANES: 20,
  MAX_NODES_PER_LANE: 50,
  MAX_CONNECTIONS: 200,
  MAX_PHASES: 10,
  MIN_NODE_TEXT_LENGTH: 1,
  MAX_NODE_TEXT_LENGTH: 100,
  MAX_DESCRIPTION_LENGTH: 500,
};
